[
    # {"name": "rabi",
    #  "substitutions": {"name":  "uncond_pi2",
    #                    "PULSE": "unconditional_pi2_pulse",
    #                    "TYPE":  "unconditional pi/2 pulse"}},
    # {"name": "rabi",
    #  "substitutions": {"name":  "uncond_pi",
    #                    "PULSE": "unconditional_pi_pulse",
    #                    "TYPE":  "unconditional pi pulse"}},
    # {"name": "rabi",
    #  "substitutions": {"name":  "cond_pi",
    #                    "PULSE": "conditional_pi_pulse",
    #                    "TYPE":  "conditional pi pulse"}},
    # {"name": "spectro_qubit",
    #  "substitutions": {"name": "coarse",
    #                    "TYPE": "coarse"}},
    # {"name": "spectro_qubit",
    #  "substitutions": {"name": "fine",
    #                    "TYPE": "fine"}},
    {"name": "spectro_ro",
     "substitutions": {"name": "phase_only",
                       "TYPE": "phase_only"}}
]
